apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-security-context-audit
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-pod-security-context
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - ginflix
      validate:
        message: "Pod spec.securityContext.runAsNonRoot must be set to true"
        pattern:
          spec:
            securityContext:
              runAsNonRoot: true
    - name: require-container-security-context
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - ginflix
      validate:
        message: "Each container must define securityContext with readOnlyRootFilesystem and allowPrivilegeEscalation=false"
        foreach:
          - list: "request.object.spec.containers"
            pattern:
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
