apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: ginflix
  labels:
    app: database
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
    - port: 27017
      targetPort: 27017
