apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ginflix
  labels:
    app: backend
    security.ginflix.io/hardening: "enabled"
  annotations:
    security.ginflix.io/notes: "Durcissement pod applique (seccomp, no privilege escalation, SA token off)."
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-sa
      # Evite de monter automatiquement un token Kubernetes inutile dans le pod.
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      imagePullSecrets:
        - name: regcred
      containers:
        - name: backend
          image: registry.gin-telecom.ovh/ginflix/backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 50051
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: ginflix-config
            - secretRef:
                name: ginflix-app-secrets
            - secretRef:
                name: ginflix-garage-credentials
          #...
          #readinessProbe:
          #  httpGet:
          #    path: /healthz
          #    port: 8080
          #  initialDelaySeconds: 5
          #  periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: "300m"
              memory: "256Mi"
            limits:
              cpu: "2"
              memory: "512Mi"
